CREATE TABLE IF NOT EXISTS units (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type ENUM('Patrol Car','Motorbike','Tow Truck','Supervisor') NOT NULL,
  status ENUM('Available','En Route','On Scene','Unavailable') NOT NULL DEFAULT 'Available',
  location VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS incidents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(100) NOT NULL,
  severity ENUM('Low','Medium','High','Critical') NOT NULL,
  location VARCHAR(160) NOT NULL,
  status ENUM('Open','In Progress','Cleared') NOT NULL DEFAULT 'Open',
  reported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  assigned_unit_id BIGINT UNSIGNED NULL,
  CONSTRAINT fk_incidents_assigned_unit
    FOREIGN KEY (assigned_unit_id) REFERENCES units(id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  detail VARCHAR(400) NOT NULL,
  level ENUM('Advisory','Warning','Critical') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Cameras
CREATE TABLE IF NOT EXISTS cameras (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  status ENUM('Online','Offline') NOT NULL DEFAULT 'Online',
  img VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Intersections / Signals
CREATE TABLE IF NOT EXISTS intersections (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL UNIQUE,
  state ENUM('Red','Yellow','Green') NOT NULL DEFAULT 'Green',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
